from os.path import join

output_dir = 'output'

languages = ['es', 'en']
#languages = ['es', 'en', 'fr']
greetings = ['hello', 'goodbye']
greeting_template = join(output_dir, 'L={language}_G={greeting}.txt')

## 0. A rule that is not general
rule spanish_hello:
    output:
        join(output_dir, 'L=es_G=hello.txt')
    shell:
        '''
        python greet.py \\
            --language es \\
            --greeting hello \\
            --output {output}
        '''

## 1. A rule that will produce targets that look like the template
rule greet:
    output:
        greeting_template
    shell:
        '''
        python greet.py \\
            --language {wildcards.language} \\
            --greeting {wildcards.greeting} \\
            --output {output}
        '''
## 2. A rule that requires a file that `greet` can create
rule french_goodbye:
    input:
        join(output_dir, 'L=fr_G=goodbye.txt')

# 3. A rule to create all combinations of greetings and langauges
rule all:
    input:
        expand(greeting_template, language=languages, greeting=greetings)